### ISSUE TITLE
Path /srv/jekyll could not reflect volumes

### ISSUE THREAD

**Issue by vincentkwok** [jekyll/docker#132]
docker-compose.yml like this

```yml
version: '2'
services:
  blog:
    image: jekyll/jekyll
    ports: 
      - "4000:4000"
    volumes:
      - ./blog:/srv/jekyll
```

volume is set but `/srv/jekyll` does not have `./blog` after container created. It works in other directories. Any config I miss?
