### ISSUE TITLE
Getting "Invalid or unexpected token" exception whenever modifying a .js file

### ISSUE THREAD

**Issue by ohmeow** [jekyll/docker#141]
Using the jekyll/jekyll:pages image to run a Jekyll app on Windows via Docker.

Whenever I add some valid JavaScript and reload the page, I get an "Invalid or unexpected token" token and just see a bunch of ******** in the chrome dev tools.

My docker-compose file looks like this:
```
jekyll:
    image: jekyll/jekyll:pages
    command: jekyll serve --force_polling --config _config.yml,_config.dev.yml 
    ports:
        - 4000:4000
    volumes:
        - .:/srv/jekyll
```
