### ISSUE TITLE
Production environment variable not respected. 

### ISSUE THREAD

**Issue by PhilThurston** [jekyll/docker#153]
Currently when using the docker it does not respect the production variable. Setting the variable in the script nor setting it in the command line works. The two following yaml's **will build without error** but it will build the default "development" environment that jekyll does by default. 
Building from a ruby based docker image and installing everything works as it should. The third yaml below works. This is a problem that is isolated to the docker image.

```yaml
Build Jekyll Production:
  stage: build
  image: jekyll/builder:latest
  variables:
    JEKYLL_ENV: production
  script:
    - jekyll build -d _site
  artifacts:
    paths:
      - _site
    expire_in: 1 week
  only:
    - tags
```

```yaml
Build Jekyll Production:
  stage: build
  image: jekyll/builder:latest
  script:
    -  JEKYLL_ENV: production jekyll build -d _site
  artifacts:
    paths:
      - _site
    expire_in: 1 week
  only:
    - tags
```

```yaml
Build Jekyll Production:
  stage: build
  image: ruby:2.4
  variables:
    JEKYLL_ENV: production
  before_script:
    - bundle install
  script:
    - jekyll build -d _site
  artifacts:
    paths:
      - _site
    expire_in: 1 week
  cache:
    key: "$CI_JOB_STAGE"
    untracked: true
    paths:
      - vendor/ruby
      - vendor/bundle
  only:
    - tags
```

**Comment by envygeeks** [comment]
At this point I'm going to assume this is a problem with your scripts and not with our image:

```
jordon@doctor ~ → docker run --rm -e JEKYLL_ENV=production -it jekyll/jekyll bash
```

```
bash-4.3# /usr/local/bin/jekyll b
From: /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/exe/jekyll @ line 9 :

     4: $LOAD_PATH.unshift(File.join(File.dirname(__FILE__), "..", "lib"))
     5: 
     6: require "jekyll"
     7: require "mercenary"
     8: require "pry"
 =>  9: binding.pry
    10: 
    11: Jekyll::PluginManager.require_from_bundler
    12: 
    13: Jekyll::Deprecator.process(ARGV)
    14: 

[1] pry(main)> ENV["JEKYLL_ENV"]
=> "production"
```

**Comment by PhilThurston** [comment]
To add to this, we are using gitlab and using that exact yaml which would be the whole script since it is all CLI and not calling anything external. The third yaml would use the gem files when using bundler but that is working as it should.

**Comment by envygeeks** [comment]
This repository only concerns itself with Native Docker, and Docker, it does not concern itself with Gitlab, Docker through Gitlab, or anything else along those lines, those bugs belong to them, not to us.

**Comment by PhilThurston** [comment]
That is the docker that is being used 
`jekyll/builder:latest ID=sha256:a3bdf50fe54b1d3ca789892afbebb4338051ff3b18ba0171c633669891b25a5c` it wouldn't be something related to gitlab. please test it yourself to see the same results.

**Comment by tkulka** [comment]
@PhilThurston try this configuration:

```yml
build:
  stage: build
  image: jekyll/builder:latest
  variables:
    JEKYLL_ENV: production
    BUNDLE_BIN_PATH: $CI_PROJECT_DIR/vendor
  before_script:
    - bundle install --gemfile $(pwd)/Gemfile
  script:
    - jekyll build -s $(pwd) -d $(pwd)/_site
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - vendor/
  artifacts:
    paths:
      - _site/
    expire_in: 1 week
```

**Comment by PhilThurston** [comment]
It works! One issue though, now it is doing production every single time even with `JEKYLL_ENV: production` removed. I tried stripping everything I could think of that would be holding onto that variable. Below is the current yaml I'm using and it is still outputing production each time.

```
Build Jekyll:
  stage: build
  image: jekyll/builder:latest
  variables:
    BUNDLE_BIN_PATH: $CI_PROJECT_DIR/vendor
  before_script:
    - bundle install --gemfile $(pwd)/Gemfile
  script:
    - jekyll build -s $(pwd) -d $(pwd)/_site
  artifacts:
    paths:
      - _site/
    expire_in: 1 week
  only:
    - branches
```
