### ISSUE TITLE
ruby: No such file or directory -- serve (LoadError)

### ISSUE THREAD

**Issue by peavers** [jekyll/docker#180]
With a "out the box" clean build of Jekyll, I can't build the docker container using the following docker-compose file. 

```
version: '3'
services:
  jekyll:
    container_name: blog
    image: jekyll/jekyll:latest
    command: "jekyll serve"
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
```
Executing with `docker-compose up -d` returns 
```
Starting blog ... 
Starting blog ... done
Attaching to blog
blog | ruby: No such file or directory -- serve (LoadError)
blog exited with code 1
```
