### ISSUE TITLE
docker-compose doesn't find _config.yml

### ISSUE THREAD

**Issue by schoenwaldnils** [jekyll/docker#184]
When I use the recommended docker-compose example, jekyll can't find my `_config.yml`

```yml
// docker-compose.yml
version: '3'

services:
  jekyll:
    image: jekyll/minimal:3.4.4
    volumes:
      - $PWD:/srv/jekyll
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      -   80:4000
    command: jekyll serve
    restart: always
```

```bash
Attaching to website_jekyll_1
jekyll_1   | Configuration file: none
jekyll_1   |             Source: /srv/jekyll
jekyll_1   |        Destination: /srv/jekyll/_site
jekyll_1   |  Incremental build: disabled. Enable with --incremental
jekyll_1   |       Generating...
jekyll_1   |                     done in 0.006 seconds.
```

`Configuration file: none`
And I can't see why :/

my folder structure:
```
- root
-- _config.yml
-- src
--- all the jekyll stuff
```
and I set `source`in the `_config.yml` to `src`
```
source: src
```
