### ISSUE TITLE
Docker-compose example on README doesn't work

### ISSUE THREAD

**Issue by aom** [jekyll/docker#188]
I took the example `docker-compose.yml` from `README.md` and only added version number to top (tried with 2.1 as well). I also tried `:latest` tag.

```
➜  cat docker-compose.yml
version: '3'

services:
  site:
    command: jekyll serve
    image: jekyll/jekyll:3.5
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      -   80:4000
➜  docker-compose run site jekyll new site
su-exec: new: No such file or directory
```

I am unfamiliar with [su-exec](https://github.com/ncopa/su-exec) which seems to be causing issues here.

I'm using Docker for Mac:

Version 17.09.0-ce-mac35 (19611)
Channel: stable
a98b7c1b7c
