### ISSUE TITLE
Bundles are not installed in `/vendor/bundle`, cannot launch server offline

### ISSUE THREAD

**Issue by T3sT3ro** [jekyll/docker#348]
When starting a `jekyll/jekyll:4.0` (and `4.2.2`) with volume `./vendor/bundle:/usr/local/bundle:Z`, installed gems don't cache locally. They install into `/usr/gem`, so starting jekyll server without internet access is impossible.

I tried attaching to container and doing any combination of `bundle cache`, `bundle package`, `bundle update`, `bundle install`, `bundle install --deployment`, but nothing populates the `vendor/bundle`...

Here is my docker-compose.yml:

```yml
services:

  jekyll-server:
    image: jekyll/jekyll:4.2.2
    volumes:
      - .:/srv/jekyll:Z
      - ./vendor/bundle:/usr/local/bundle:Z
    ports:
      - '[::1]:4000:4000'
      - '[::1]:35729:35729'
    command: jekyll serve --livereload

  bundle-install: 
    image: jekyll/jekyll:4.2.2
    volumes:
      - .:/srv/jekyll:Z
      - ./vendor/bundle:/usr/local/bundle:Z # mount to update gems cache
    command: bundle update
    ```
